import Foundation

struct SoundInfo: Codable, Hashable {
    let file: String
    let title: String
}

/// The bundled pool of alarm sounds (generated by scripts/generate_sounds.py).
final class SoundLibrary {
    static let shared = SoundLibrary()

    let sounds: [SoundInfo]

    private init(bundle: Bundle = .main) {
        var list: [SoundInfo] = []
        if let url = bundle.url(forResource: "Sounds", withExtension: "json"),
           let data = try? Data(contentsOf: url),
           let decoded = try? JSONDecoder().decode([SoundInfo].self, from: data) {
            list = decoded.filter { bundle.url(forResource: $0.file, withExtension: nil) != nil }
        }
        if list.isEmpty {
            list = (bundle.urls(forResourcesWithExtension: "caf", subdirectory: nil) ?? [])
                .map(\.lastPathComponent)
                .sorted()
                .map { SoundInfo(file: $0, title: ($0 as NSString).deletingPathExtension) }
        }
        sounds = list
    }

    /// A different sound for every calendar day (see SoundRotation).
    func sound(for date: Date, timeZone: TimeZone) -> SoundInfo? {
        guard !sounds.isEmpty else { return nil }
        let day = SoundRotation.dayNumber(for: date, timeZone: timeZone)
        return sounds[SoundRotation.index(forDay: day, count: sounds.count)]
    }
}
